attempting to fix codeql not compiling.     only testing debug clang currently.

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -13,11 +13,11 @@ name: "CodeQL Advanced"
 
 on:
   push:
-    branches: [ "main", "inDev" ]
+    branches: ["**"]
   pull_request:
-    branches: [ "main", "inDev" ]
+    branches: ["**"]
   schedule:
-    - cron: '24 23 * * 1'
+    - cron: '00 00 * * 1'
 
 jobs:
   analyze:
@@ -27,7 +27,7 @@ jobs:
     #   - https://gh.io/supported-runners-and-hardware-resources
     #   - https://gh.io/using-larger-runners (GitHub.com only)
     # Consider using larger runners or machines with greater resources for possible analysis time improvements.
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+    runs-on: ${{ 'ubuntu-latest' }}
     permissions:
       # required for all workflows
       security-events: write
@@ -58,12 +58,26 @@ jobs:
     steps:
     - name: Checkout repository
       uses: actions/checkout@v4
+      with:
+        submodules: recursive
 
     # Add any setup steps before running the `github/codeql-action/init` action.
     # This includes steps like installing compilers or runtimes (`actions/setup-node`
     # or others). This is typically only required for manual builds.
     # - name: Setup runtime (example)
     #   uses: actions/setup-example@v1
+    - name: Install Clang 18
+      uses: egor-tensin/setup-clang@v1
+      with:
+        version: 18
+    
+    - name: Verify Clang
+      run: |
+          if [[ "$(clang --version)" != *"18"* ]]; then
+            echo "Error: Clang 18 is required!";
+            exit 1;
+          fi
+
 
     # Initializes the CodeQL tools for scanning.
     - name: Initialize CodeQL
@@ -86,7 +100,10 @@ jobs:
     # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
     - if: matrix.build-mode == 'manual'
       shell: bash
-      run: mkdir build; cmake -S . -G Ninja -B build; cmake --build build;
+      run: |
+          git submodule update --init --recursive;
+          mkdir build;
+          cmake --preset=clangDebug -S . -B build;
 
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
